INSERT INTO recipes (id, name, description, ingredients, steps) VALUES
    ('a10a6c81-0e50-4c57-aeaa-8f3e0a8b34f1', 'Pasta Carbonara', 'Classic Italian pasta dish with bacon and eggs',
     ARRAY['Spaghetti', 'Bacon', 'Eggs', 'Parmesan cheese', 'Black pepper', 'Salt'],
     ARRAY['1. Cook the spaghetti until al dente.', '2. In a pan, cook the bacon until crispy.',
           '3. In a bowl, whisk together eggs, Parmesan cheese, black pepper, and salt.',
           '4. Drain the cooked spaghetti and add it to the pan with bacon.',
           '5. Pour the egg mixture over the spaghetti and toss until coated.']),
    ('c6fb8e89-4809-4f32-b813-70e97456e7c6', 'Chicken Stir-Fry', 'Quick and easy stir-fry with chicken and vegetables',
     ARRAY['Chicken breast', 'Bell peppers', 'Broccoli', 'Carrots', 'Soy sauce', 'Garlic', 'Ginger'],
     ARRAY['1. Slice the chicken breast into thin strips.', '2. Heat oil in a pan or wok.',
           '3. Add minced garlic and ginger and cook for a minute.',
           '4. Add the chicken strips and stir-fry until cooked through.',
           '5. Add sliced bell peppers, broccoli, and carrots.',
           '6. Cook for a few minutes until the vegetables are tender-crisp.',
           '7. Add soy sauce and stir to combine.']),
    ('f9d5fb2f-1c34-4b03-8e4f-2e4fbcfb8c74', 'Caprese Salad', 'Simple and refreshing Italian salad with tomatoes and mozzarella',
     ARRAY['Tomatoes', 'Fresh mozzarella cheese', 'Fresh basil leaves', 'Olive oil', 'Balsamic glaze', 'Salt', 'Pepper'],
     ARRAY['1. Slice tomatoes and mozzarella cheese into rounds.',
           '2. Arrange alternating slices of tomatoes and mozzarella on a plate.',
           '3. Place fresh basil leaves on top.',
           '4. Drizzle with olive oil and balsamic glaze.',
           '5. Sprinkle with salt and pepper.']);
